name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  check:
    timeout-minutes: 5
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./...
